
<Canvas_Test_View>:
<MySplitter>:

<Main_app>:
	id: mainApp
	FloatLayout:
		GridLayout:
			cols: 1
			pos_hint: {"top": 1, "left": 1}
			size_hint: 1, 1
			GridLayout:
				cols: 2
				pos_hint: {"top": 1, "left": 1}
				size_hint: 1, 1
				StencilView:
					id: stencil
					Canvas_Test_View:
						id: scatter
						pos: stencil.pos
						size: my_image.size
						do_rotation: False
						AsyncImage:
							id: my_image
							myid: 'map'
							source: 'image/level1.jpg'
							size: stencil.width, stencil.height
						DragableButton:
							text: "Button"
							size_hint: None, None
							size: "50dp", "50dp"
							pos: "100dp", "200dp"
							drag_rectangle: self.x, self.y, self.width, self.height
							drag_timeout: 10000000
							drag_distance: 0
				Splitter:
					sizable_from: "left"
					size_hint: .3, 1
					min_size: "10dp"
					max_size: "300dp"
					width: "200dp"
					Button:
						size_hint: None, None
						size: "100dp", "50dp"
						text: 'ChangePicture'
						on_press: mainApp.on_button_click()
			Button:
				size_hint: None, None
				size: "100dp", "50dp"
				text: 'ChangePicture'
				on_press: mainApp.on_button_click()

